import express from 'express';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import {execFile, spawn} from 'child_process';
import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.join(__dirname,'..','repositories'); fs.mkdirSync(ROOT,{recursive:true});
const app=express(); const upload=multer({dest:path.join(__dirname,'uploads')});
app.use(express.json({limit:'2mb'})); app.use(express.static(path.join(__dirname,'../public')));
const safe=(p)=>path.resolve(ROOT,p).startsWith(ROOT+path.sep)?path.resolve(ROOT,p):null;
app.get('/api/repos',(req,res)=>res.json(fs.readdirSync(ROOT,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name)));
app.post('/api/repos',(req,res)=>{const n=String(req.body.name||'').trim(); if(!/^[\w.-]+$/.test(n)) return res.status(400).json({error:'Invalid repository name'}); const p=safe(n); if(fs.existsSync(p)) return res.status(409).json({error:'Repository exists'}); fs.mkdirSync(p); res.json({ok:true});});
app.get('/api/tree',(req,res)=>{const base=safe(req.query.repo||''); if(!base||!fs.existsSync(base)) return res.status(404).end(); function walk(d){return fs.readdirSync(d,{withFileTypes:true}).map(x=>({name:x.name,type:x.isDirectory()?'dir':'file',path:path.relative(ROOT,path.join(d,x.name)).replaceAll('\\','/'),children:x.isDirectory()?walk(path.join(d,x.name)):undefined}));} res.json(walk(base));});
app.get('/api/file',(req,res)=>{const p=safe(req.query.path||''); if(!p||!fs.existsSync(p)||!fs.statSync(p).isFile()) return res.status(404).end(); res.type('text/plain').send(fs.readFileSync(p,'utf8'));});
app.post('/api/file',(req,res)=>{const p=safe(req.body.path||''); if(!p)return res.status(400).end(); fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p,String(req.body.content??'')); res.json({ok:true});});
app.post('/api/dir',(req,res)=>{const p=safe(req.body.path||''); if(!p)return res.status(400).end(); fs.mkdirSync(p,{recursive:true}); res.json({ok:true});});
app.delete('/api/path',(req,res)=>{const p=safe(req.body.path||''); if(!p||p===ROOT)return res.status(400).end(); fs.rmSync(p,{recursive:true,force:true}); res.json({ok:true});});
app.post('/api/upload',upload.single('file'),(req,res)=>{try{const p=safe(req.body.path||''); if(!p||!req.file)return res.status(400).end(); fs.mkdirSync(path.dirname(p),{recursive:true}); fs.renameSync(req.file.path,p); res.json({ok:true});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/run-python',(req,res)=>{const p=safe(req.body.path||''); if(!p||!fs.existsSync(p))return res.status(404).json({error:'File not found'}); execFile('python3',[p],{cwd:path.dirname(p),timeout:10000,maxBuffer:1024*1024},(err,stdout,stderr)=>res.json({code:err?.code??0,stdout,stderr,error:err?.message||''}));});
app.post('/api/terminal',(req,res)=>{const repo=String(req.body.repo||''); const cwd=safe(repo); const command=String(req.body.command||''); if(!cwd||!fs.existsSync(cwd))return res.status(404).end(); if(!command)return res.json({output:''}); const child=spawn('/bin/sh',['-lc',command],{cwd}); let out=''; child.stdout.on('data',d=>out+=d); child.stderr.on('data',d=>out+=d); child.on('close',code=>res.json({code,output:out}));});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));
app.listen(process.env.PORT||3000,()=>console.log('Repo IDE running on http://localhost:'+(process.env.PORT||3000)));
